
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: viagem-backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
    working_dir: /var/www
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
    container_name: viagem-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: viagem-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - ./backend/docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"