
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: viagem-backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
    working_dir: /var/www

  frontend:
    build:
      context: ./frontend
    container_name: viagem-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: viagem-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3309:3306"